#!/bin/bash
 ###########################################################################
# Copyright 2017 IoT.bzh
#
# author: Sebastien Douheret <sebastien@iot.bzh>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###########################################################################

. $(dirname "$0")/_env-init.sh

if [[ "${1}" == "" || "${1}" != "${SDK_ROOT_DIR}"* ]]; then
    echo "Invalid sdk root directory"
    exit 1
fi

if [ ! -d "${1}" ]; then
    echo "sdk directory doesn't exist"
    exit 1
fi

rm -rf "${1}" && echo "SDK successfully removed."

# Potentially remove parent directory when it is the latest SDK for this version
rmdir "$(dirname ${1})"

exit 0
